config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'posts#index'

  get 'pages/index', to: 'pages#index'
  get 'users/:id/likes', to: 'users#likes'
  post "comments/:id/destroy" => "comments#destroy"
  post "comments/:id/destroy" => "comments#destroy"
  delete 'comments/:id', to: 'comments#destroy'


  resources :users, only: [:show, :edit]

  


    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
      collection do
        get :search
      end
    end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  include RansackerTranslator
  
  ransacker_translate :title, :tags_name, :user_name, :user_nickname
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user 
  belongs_to :post
  validates :comment, presence: true, length: { maximum: 50 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30 }
  validates :image, presence: true
  validates :user_id, {presence: true}
  belongs_to :user
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  

  mount_uploader :image, ImageUploader

  def user
    return User.find_by(id: self.user_id)
  end

  acts_as_taggable

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, :omniauthable
  
  has_many :posts, :dependent => :destroy
  has_many :comments, foreign_key: 'user_id', dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  def self.find_for_oauth(auth)
   user = User.where(uid: auth.uid, provider: auth.provider).first

   unless user
     user = User.create(
       uid:      auth.uid,
       provider: auth.provider,
       email:    User.dummy_email(auth),
       password: Devise.friendly_token[0, 20],
       image: auth.info.image,
       name: auth.info.name,
       nickname: auth.info.nickname,
       )
   end

   user
  end
  

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  private

  def self.dummy_email(auth)
   "#{auth.uid}-#{auth.provider}@example.com"
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_current_user
  before_action :authenticate_user!
  before_action :set_search
  include RansackerTranslator::FormatRansackParameters
  before_action :format_ransack_params
  
  
  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
  
  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to("/pages/index")
      end
  end


  

  def after_sign_in_path_for(resource)
    user_path(resource.id)
  end

  def set_search
    if params[:q].present?
    keywords = params[:q][:title_or_tags_name_or_user_name_or_user_nickname_cont].split(/[\p{blank}\s]+/)

    @search = Post.ransack(
      combinator: 'and',
      groupings: { 'a' => {title_or_tags_name_or_user_name_or_user_nickname_cont: keywords[0]}, 'b' => {title_or_tags_name_or_user_name_or_user_nickname_cont: keywords[1]}}
      )
    @search_posts = @search.result(distinct: true).order(created_at: "DESC").page(params[:page]).per(20) 

  else

    groupings = [] 
      @search = Post.ransack(
      combinator: 'and',
      groupings: groupings
     )
     @search_posts = @search.result(distinct: true).order(created_at: "DESC").page(params[:page]).per(20) 

  end

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.build(comment_params)
    @comment.user_id = current_user.id
    @post = @comment.post
    if @comment.save
      flash[:notice] = 'コメントが送信されました'
      redirect_back(fallback_location: root_path)
    else
      flash[:notice] = 'コメントの投稿に失敗しました。コメントが入力されていないまたは50文字以上入力されています。'
      
      redirect_back(fallback_location: root_path)
    end
 end

    def destroy
      @comment = Comment.find_by(id: params[:post_id])
      @comment.destroy
      flash[:notice]  = 'コメントを削除しました。'
      redirect_back(fallback_location: root_path)
    end  


  private
  def comment_params
    params.require(:comment).permit(:comment)
  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_current_user_post, only: [:destroy]
  before_action :authenticate_user!

  def index
    @posts = Post.page(params[:page]).per(15).order(created_at: :desc)

  end



  def new
    @post = current_user.posts.build
  end


  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      flash[:notice] = "記事が投稿されました!"
      redirect_to posts_path
    else
      render :new, flash: {
          post: @post,
          error_messages: @post.errors.full_messages
        }
    end
    
  end

  def show
    @posts = Post.all
    @post = Post.find_by(id: params[:id])
    @user = User.find_by(id: @post.user_id)
    @comments = @post.comments
    @comment = Comment.new
    @like = Like.new
    
  end


  def destroy
    post = Post.find(params[:id])
    post.delete

    redirect_to posts_path
  end
    

  def set_current_user_post
    @post = current_user.posts.find(params[:id])
  end



  def ensure_correct_user
    @post = Post.find_by(id:params[:id])
    if @post.user_id != @current_user.id
      flash[:notice] = "権限がありません"
      redirect_to("/posts/index")
    end
  end



  private

    # paramsから欲しいデータのみ抽出
    def post_params
        params.require(:post).permit(:title, :image, :tag_list, :user_id)
    end

    
    
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    callback_from :twitter
  end

  private
  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      print("persisted true")
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      print("persisted false")
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to controller: 'sessions', action: 'new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = Post.all.order(created_at: :desc)
    
  end

  def likes
    @user = User.find(params[:id])
    @posts = Post.all.order(created_at: :desc)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InkGrow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body class ="">
  <% if user_signed_in? %>
    <header class ="">
      <% if flash[:notice] %>
         <div class="alert alert-primary"><%= flash[:notice] %></div>
      <% end %>

      <nav class="header_menu row mt-3">
      <div class="menu">
          <div id="open_menu">
            <%= image_tag("/images/blackmenu.png") %>
          </div>
      </div>
          <li class="d-none d-sm-block">
        <%= link_to("/posts") do %>
            <%= image_tag("/images/logo.png") %>
        <% end %>
          </li>
        <li class="search_bar d-none d-md-block">
          <%= search_form_for @search do |f| %>  
            <%= f.text_field :title_or_tags_name_or_user_name_or_user_nickname_cont, 
              value: params.dig(:q,:title_or_tags_name_or_user_name_or_user_nickname_cont), 
              placeholder: "検索", 
              class: 'input w-75 rounded' %>
              <%= f.submit "検索" %>
           <% end %>
        </li>
      </nav>

      </header>    


      <div class= "row">
        



<div class="m-0 p-0 col-lg-2">
          <nav class="p-0 pt-4 m-0 sidebar col-md-2">
            <ul>
                <%= link_to("/users/#{current_user.id}") do %>
                  <li class="pl-4 pt-3">
                  <%= image_tag current_user.image, class:"rounded-circle" %>
                  <%= current_user.name %>
                  </li>
                <% end %>
                <%= link_to("/posts") do %>
                  <li class="pl-4 pt-3 row">
                    <%= image_tag("/images/house.png") %>
                    <p class="pt-2">ホーム</p>
                  </li>
                <% end %>
                  <li class="pl-4 pt-3">
                    <%= link_to image_tag("/images/exit.png"), destroy_user_session_path, class: "menu_icon" %>
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> 
                  </li>          
                <div class="ml-4 mt-3 ">
                  <%= link_to '投稿', new_post_path, class: "btn posts_button" %>
                </div>
              
            </ul>
          </nav>  
        <% end %>   


      </div>
  
  <% if user_signed_in? %>    
    <div id="whitearea">
    </div>

      <div class="container-fluid pt-5 col-12 logined_contents">
        <%= yield %>
      </div>    
    <% else %>
      <div class=" m-0 p-0 col-12 contents">
        <%= yield %>
      </div>  
  <% end %>   

      <% if user_signed_in? %>    
        <div class="container m-0 p-0  d-none">
            
        </div>
     <% end %>   


<script>
    $(function(){
  $("#open_menu").click(
    function() {
    $('.sidebar').fadeIn();
    $('#open_menu').hide();
    $('#whitearea').show();
    $('body').css('overflow','hidden');
  });

  $('#whitearea').click(
      function() {
        $('#open_menu').fadeIn();
        $('.sidebar').hide();
        $('#whitearea').hide();
        $('body').css('overflow','scroll');
    });


});

</script>


  </body>
</html>

app/views/pages/index.html.erb
<% if user_signed_in? %>
    <% else %>
      <%= link_to 'Twitterログイン', user_twitter_omniauth_authorize_path %>
 <% end %>

app/views/posts/index.html.erb
<div class="d-flex align-items-center page_head">
    <h1>投稿一覧</h1>
</div>

  <div class="container-fluid">
    <div class="row">
      <% @search_posts.each do |post| %>
        <% @user = User.find_by(id: post.user_id) %>
        <div class="card col-sm-4 col-md-3 col-lg-2 col-12 mt-3 ">
          <%= link_to("/posts/#{post.id}") do %>
            <div class="card_image d-flex align-items-center">
              <%= image_tag(post.image.url) %>
            </div>
          <% end %>
          <div class="card-body">
            <h6 class="card-title"><%= link_to post.title, "/posts/#{post.id}" %></h6>
            <div class="tweet_user">
              <%= link_to("/users/#{@user.id}") do %>
                <%= image_tag @user.image %>
                <%= @user.name %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>




<%= paginate @posts %>

app/views/posts/new.html.erb
<div class="mt-5">
  <h1>投稿</h1>
</div>

<% if flash[:error_messages] %>
    <div class="alert alert-danger">
        <ul>
            <% flash[:error_messages].each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_for @post do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="form-group">
        <div class="prev_box ">
            <div class="prev_text ">
                <%= f.file_field :image, id: :post_img %>
            </div>
            <div class="prev_image ">
                <% if @post.image.present? %>
                    <%= image_tag @posts.image, id: :img_prev %>
                <% else %>
                    <%= image_tag "", id: :img_prev %>
                <% end %>
            </div>
        </div>
    </div>

    <%# scriptここから %>
<script type="text/javascript">
  $(function() {
    function readURL(input) {
        if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
    $('#img_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
        }
    }
    $("#post_img").change(function(){
        readURL(this);
    });
  });
</script>

    <%# scriptここまで %>


    <div class="form-group">
        <%= f.text_field :title, placeholder: 'タイトル',  class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.text_field :tag_list, value: @post.tag_list.join(','), placeholder: '○○,△△,□□', class: "form-control" %>
    </div>
    <div class="form-group mb-5">
        <%= f.submit '投稿する', class: 'btn btn-info btn-block' %>
    </div>
<% end %>

app/views/posts/show.html.erb
  <div class="mx-auto p-0 text-center prev_image mt-5">
    <%= image_tag @post.image.url %>  
  </div>
  <div class="container pt-3 mt-5">
    <div class="post_menu w-100">
      <% if current_user.already_liked?(@post) %>
        <%= link_to(post_like_path(@post), method: :delete) do %>
          <span class="fa fa-heart like-btn-unlike mr-3"></span>
        <% end %>
        <p id="open_likedlist">
        <%= @post.likes.count %>名がいいね
        </p>
      <% else %>
          <%= link_to(post_likes_path(@post), method: :POST) do %>
            <span class="fa fa-heart like-btn mr-3 "></span>
          <% end %>
      <p id="open_likedlist">
        <%= @post.likes.count %>名がいいね
      </p>
      <% end %><br>
    </div>


  <div id="liked_list">
  <h5>いいねしたユーザー</h5>
    <% @post.liked_users.each do |user| %>
      <div id="liked_userlist">
        <%= link_to("/users/#{user.id}", class: 'd-flex mb-4') do %>
          <%= image_tag user.image, class:"pr-2 rounded-circle d-flex" %>
          <p class="mt-2"><%= user.name %></p>
        <% end %>    
      </div>
    <% end %>
  </div>


      

  <script>
    $(function(){
  $("#open_likedlist").click(
    function() {
    $('#liked_list').fadeIn();
    $('body').css('overflow','hidden');
    $('#whitearea').show();
  });

  $('#whitearea').click(
      function() {
        $('#liked_list').hide();
        $('body').css('overflow','scroll');
        $('#whitearea').hide();
    });
});
</script>



    <div class="">
      <h3><%= @post.title %></h3>
    </div>
  
    <div class="">
      <td><%= @post.tag_list %></td><br>
    </div>

    <div class="tweet_user m-2">
      <%= image_tag @user.image %>
      <%= link_to("/users/#{@user.id}") do %>
        <%= @user.name %>
      <% end %>
    </div>
    <% if current_user.id == @user.id %>
        <%= link_to "投稿を削除" , @post, class: 'btn btn-outline-info', method: :delete, data: {confirm: "投稿記事を削除しますか？", cancel: "キャンセル", commit: "削除する", title: "削除の確認"} %>
      <% end %>

    <div class="container mt-5">
      <h5>コメント</h5>
      <div class="row ">
      <%= image_tag current_user.image, class:"pr-2 rounded-circle mr-4" %>
      <%= form_for [@post, @comment] do |f| %>
        <%= f.text_field :comment, class: 'mt-3' %>
        <%= f.submit 'コメントする', class: "btn btn-outline-dark ml-3" %>
      <% end %>
      </div>
      <div class="border-bottom pt-5"></div>
      <% @comments.each do |comment| %>
      <div class="under_line"></div>
        <% user = User.find_by(id: comment.user_id) %>
        <div class="tweet_user pt-3 pb-1">
          <%= image_tag user.image %>
          <%= link_to("/users/#{user.id}") do %>
            <%= user.name %>
          <% end %>
        </div>
        <div class= "comments"> 
          <div class="comment">
            <p>
              <%= comment.comment %>
            </p>
          </div>
          <div class="btn delete_btn ">
            <% if current_user == user %>
              <%= link_to "コメントを削除する" ,post_comment_path(comment.id) , class: 'btn btn-outline-info ', method: :delete, data: {confirm: "コメントを削除しますか？", cancel: "キャンセル", commit: "コメントを削除する", title: "削除の確認"} %>
            <% end %>
          </div>
        </div>
        
      <% end %>

    </div>

  </div>

app/views/users/likes.html.erb
<div class="text-center user_name page_head">
  <img src="<%= @user.image %>" class = "rounded-circle">
  <h4><%= @user.name %></h4>
  <p>@<%= @user.nickname %></p>
  <% if current_user.id == @user.id %>
    <%# <p>
      <%= link_to("プロフィールを編集","/users/:id/edit") %>
    <%# </p> %>
  <% end %>

<div class="users_nav">
  <ul class="nav">
    <li class="nav-link nonactive"><%= link_to("投稿", "/users/#{@user.id}") %></li>
    <li class="nav-link active"><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
  </ul>
</div>
</div>
     
<div class="container-fluid">
  <div class="row">
    <% @user.liked_posts.each do |post| %>
      <% @user = User.find_by(id: post.user_id) %>
      <div class="card col-sm-4 col-md-3 col-lg-2 col-12 mt-3 ">
        <%= link_to("/posts/#{post.id}") do %>
          <div class="card_image d-flex align-items-center">
            <%= image_tag(post.image.url) %>
          </div>
        <% end %>
        <div class="card-body">
          <h6 class="card-title"><%= link_to post.title, "/posts/#{post.id}" %></h6>
          <div class="tweet_user">
             <%= link_to("/users/#{@user.id}") do %>
              <%= image_tag @user.image %>
                <%= @user.name %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center user_name page_head">
  <img src="<%= @user.image %>" class = "rounded-circle">
  <h4><%= @user.name %></h4>
  <p>@<%= @user.nickname %></p>
  <% if current_user.id == @user.id %>
    <%# <p>
      <%= link_to("プロフィールを編集","/users/:id/edit")
    </p>  %>
  <% end %>

<div class="users_nav">
  <ul class="nav">
    <li class="nav-link active"><%= link_to("投稿", "/users/#{@user.id}") %></li>
    <li class="nav-link nonactive"><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
  </ul>
</div>
</div>
     
  <div class="container-fluid">
<div class="row">
      <% @user.posts.each do |post| %>
        <% @user = User.find_by(id: post.user_id) %>

  <div class="card col-sm-4 col-md-3 col-lg-2 col-12 mt-3 ">
    <%= link_to("/posts/#{post.id}") do %>
      <div class="card_image d-flex align-items-center">
        <%= image_tag(post.image.url) %>
      </div>
    <% end %>
    <div class="card-body">
      <h6 class="card-title"><%= link_to post.title, "/posts/#{post.id}" %></h6>  
    </div>
  </div>

      <% end %>
    
</div>
</div>





    